# Set Build flags

set(CMAKE_CXX_FLAGS_WURF_RELEASE "-O0 -g")
set(CMAKE_C_FLAGS_WURF_RELEASE "-O0 -g")
set(CMAKE_EXE_LINKER_FLAGS_WURF_RELEASE "-O0 -g")
set(CMAKE_SHARED_LINKER_FLAGS_WURF_RELEASE "-O0 -g")

if (CMAKE_BUILD_TYPE STREQUAL "WurfRelease")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_WURF_RELEASE}")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_WURF_RELEASE}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${CMAKE_EXE_LINKER_FLAGS_WURF_RELEASE}")
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${CMAKE_SHARED_LINKER_FLAGS_WURF_RELEASE}")
endif()
